### ISSUE TITLE
[Bug] AddHostedTemporalWorker is not defined

### ISSUE THREAD

**Issue by eugbyte** [temporalio/samples-dotnet#51]
### Describe the bug
The extension method `AddHostedTemporalWorker` is not found anywhere in the projec, nor the namespace `using Temporalio.Extensions.Hosting`, although they are mentioned in the [samples](https://github.com/temporalio/samples-dotnet/blob/842af52447ec212fb004ff5056df1b266a194f1f/src/DependencyInjection/Program.cs#L15).

**Comment by cretz** [comment]
This is used [here](https://github.com/temporalio/samples-dotnet/blob/842af52447ec212fb004ff5056df1b266a194f1f/src/DependencyInjection/Program.cs#L15) and it compiles successfully because it is an extension method on `IServiceCollection` in the `Microsoft.Extensions.DependencyInjection` namespace when the `Temporalio.Extensions.Hosting` is depended on. See the [README](https://github.com/temporalio/sdk-dotnet/tree/main/src/Temporalio.Extensions.Hosting) for the `Temporalio.Extensions.Hosting` project. [Here](https://github.com/temporalio/sdk-dotnet/blob/ba4763bfcbe3a11d818cc92b22eab21d93aacf35/src/Temporalio.Extensions.Hosting/TemporalHostingServiceCollectionExtensions.cs#L31) is where it is defined.

Feel free to join is on the `#dotnet-sdk` channel on Slack at https://t.mp/slack and the forums for general questions. I'll close this issue, but you can continue to comment on it too.
